### ISSUE TITLE
Fullscreen app blocks wallpaper change

### ISSUE THREAD

**Issue by jeolsen** [scriptingosx/desktoppr#17]
Issue: Expand any app to Full Screen, run desktoppr to change all backgrounds, exit full screen app.  The background for that display is not set.

I'm guessing it's because full screen is treated as a new virtual display so it is actually setting that background.  But once the full screen app is closed it gets rid of that virtual display and goes back to the normal display which hadn't been set.

If desktoppr could be changed to set the non-visible displays as well, then when the full screen app closes and the normal display comes back it would have been set there as well.

**Comment by scriptingosx** [comment]
Your diagnosis is correct. And yes, it would be totally wonderful if desktoppr could set the background image on non-visible screens, but the API does not allow that and I am not aware of any way to achieve this. See also #2 and #8.
