### ISSUE TITLE
image scaling doesn't work via MDM

### ISSUE THREAD

**Issue by kylejericson** [scriptingosx/desktoppr#18]
I looked at this https://github.com/scriptingosx/desktoppr/releases/tag/v0.3

When I try to run this via Jamf it doesn't work due to the spaces for the command.

`desktoppr scale center`

`/usr/local/bin/desktoppr "/Library/Desktop Pictures/BoringBlueDesktop.png" scale center`

Is there a info on how to do this?

**Comment by scriptingosx** [comment]
The scale verb doesn’t take a file path. You set the image first with

```
/usr/local/bin/desktoppr "/Library/Desktop Pictures/BoringBlueDesktop.png"
```

and then set the scale by calling desktoppr again

```
/usr/local/bin/desktoppr scale center
```
