### ISSUE TITLE
desktoppr won't read the current desktop picture when a feature to automatically change a wallpaper is enabled.

### ISSUE THREAD

**Issue by EugeneTarasenko** [scriptingosx/desktoppr#20]
When a feature to automatically change the wallpaper every `n` minutes is enabled, **desktoppr** won't display the path of the current wallpaper, only the folder where that wallpaper is located.

Can it be fixed? 

<img width="368" alt="Screen Shot 2023-11-07 at 17 31 13" src="https://github.com/scriptingosx/desktoppr/assets/87163666/7813bf82-6959-4444-b18b-6f3f89877bce">

**Comment by scriptingosx** [comment]
No, the API desktoppr uses does not provide that information.
