### ISSUE TITLE
Feature Request: Add support for scaling keys

### ISSUE THREAD

**Issue by WardsParadox** [scriptingosx/desktoppr#3]
I think it would be great if desktoppr could also set the scaling keys when setting the desktop.

NSWorkspace has support for the scaling the images:
https://developer.apple.com/documentation/appkit/nsworkspace/1527228-setdesktopimageurl
https://developer.apple.com/documentation/appkit/nsworkspace/desktopimageoptionkey
https://developer.apple.com/documentation/appkit/nsimagescaling

**Comment by scriptingosx** [comment]
I am not so sure. The System Preferences UI doesn't expose those options any more. Can you describe your particular use case?

**Comment by WardsParadox** [comment]
10.15 still shows the ability to set the machine to Stretch to Fill Screen, Center, Tile, Fit to Screen and Fill to Screen. Mostly what the keys in the first link I specified. You can also set the background color for the bars in a non-fitting wallpaper via the same gui. 

When our machines are first bootstrapped for new staff, the default dock is set. We also set a default wallpaper, I'm currently doing this via pyobjc, but would love to be able to have a tool we can push down for it or for student machines when we do lab setups (combined with a generated wallpaper per machine).
 Relevant pyobjc code used:
```python
file_url = NSURL.fileURLWithPath_(picture_path)

# make image options dictionary
NSWorkspaceDesktopImageScalingKey = u'NSWorkspaceDesktopImageScalingKey'



options = {}
options[NSWorkspaceDesktopImageScalingKey] = NSImageScaleAxesIndependently
options[NSWorkspaceDesktopImageAllowClippingKey] = True

# get shared workspace
ws = NSWorkspace.sharedWorkspace()

# iterate over all screens
for screen in NSScreen.screens():
    # tell the workspace to set the desktop picture
    (result, error) = ws.setDesktopImageURL_forScreen_options_error_(
        file_url, screen, options, None)
```


![Screen Shot 2019-06-17 at 7 54 31 AM](https://user-images.githubusercontent.com/8117192/59609784-487b8880-90d5-11e9-8c9c-0a5e4bb2c199.png)

**Comment by scriptingosx** [comment]
I have to admit, the main reason I am reluctant is that it would make argument parsing, _much_ harder. But I'd _like_ to have it in there as well. I will think about this.

**Comment by WardsParadox** [comment]
👍 I might learn me some swift to assist.

**Comment by scriptingosx** [comment]
implemented in [v0.3](https://github.com/scriptingosx/desktoppr/releases/tag/v0.3), please test!

**Comment by WardsParadox** [comment]
testing today.
Color is the hex value only right? No need for a pound/hashtag/number symbol right?

**Comment by scriptingosx** [comment]
yes, just a six digit hex value

**Comment by WardsParadox** [comment]
Thought color wasn't working for a bit there, but that was due to the image I was using not working as intended. Seems to work here 👍🏻 Thanks!
