### ISSUE TITLE
Trouble using via Jamf

### ISSUE THREAD

**Issue by tep74** [scriptingosx/desktoppr#4]
I can run desktoppr fine on my local Mac, but when I try to execute via Jamf, either nothing happens or I get '_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.'

I'm using a script to run the command as the user:
#!/bin/sh

user=`ls -l /dev/console | awk {' print $3 '}`
su $user -c '/usr/local/bin/desktoppr /Users/Shared/Desktop.jpg'

The permissions are the same on my Mac and my test machines...

**Comment by GabeShack** [comment]
Im still seeing this issue in 10.15.6

There is no change when running from JAMF but is working from the local command line.  Using the script from your examples has no change as well.

**Comment by Greyeye** [comment]
I've changed it to use launchctl "asuser" 
and it finally worked.


```# get the current user
loggedInUser=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }')
loggedInuid=$(id -u "$loggedInUser")

if [ "$loggedInUser" != "loginwindow" ]; then
    # set the desktop for the user
    echo "logged in user $loggedInUser"
    /bin/launchctl asuser "$loggedInuid" sudo -u "$loggedInUser" "$desktoppr" "$picturepath"
else
    echo "no user logged in, no desktop set"
fi```

**Comment by scriptingosx** [comment]
I have begun using `launchctl` _and_ `sudo` to cover all situations where either doesn't work. I have updated the sample script at 

https://github.com/scriptingosx/desktoppr/blob/master/examples/setdesktop.sh
