### ISSUE TITLE
feature request: random wallpaper selection

### ISSUE THREAD

**Issue by windowswithoutborders** [scriptingosx/desktoppr#6]
Hi there,

As a very novice command line enthusiast I was looking for a way to set wallpapers on macOS in a similar and simple way as I do on linux (where I use a program called feh). After initially finding m-cli and discovering the hard way that it is a grossly outdated program (the wallpaper function turned my screen black and I had to [delete the dock folder in application support](https://github.com/rgcr/m-cli/issues/146) to get things back to normal), I eventually stumbled upon desktoppr thanks to google and can say I am very pleased! 

Your tool is great, I don't think there's much basic functionality left to add that one could ask for, but I would like to make the suggestion of adding the ability to select a random image file within a folder to set as a wallpaper. This is a feature of feh that really grew on me as I have a wallpaper folder but very infrequently switch from one I have set. With feh I just set the program to my wallpaper folder and let it choose one at random. Additionally, this is something I have done on startup every time I boot into linux.

Some quick googling [led me to a solution](https://stackoverflow.com/questions/414164/how-can-i-select-random-files-from-a-directory-in-bash) that can be used in the meanwhile through the following command: `shuf -ezn 1 /path/to/wallpaper_folder/* | xargs -0 -n1 desktoppr` .  Worth noting that shuf may not come preinstalled in macos, but I believe is included in a package you can get through brew called `coreutils`. It would be great if it were possible to implement this natively within desktoppr without the need of the shuf dependency. Additionally, maybe get this on the brew repository, it deserves to be there!

Thanks again for this wonderful utility.

**Comment by scriptingosx** [comment]
Hi! Thanks for the kind feedback.

This is already sort of implemented. (But not documented.) When you set the image to a folder, e.g.

```desktoppr /Library/Desktop Pictures```

It will choose a random image file from that folder and rotate to another random image after a certain interval. I believe the default interval is 15 minutes. You can change the interval in the Desktop preference pane. (At the bottom, where it says "change picture every xx minutes".)

I have not yet found a way to control the interval from the command line. When somebody does, I will be glad to add it to `desktoppr`.
