### ISSUE TITLE
No longer setting and listing all desktops

### ISSUE THREAD

**Issue by mottertektura** [scriptingosx/desktoppr#8]
desktoppr is not setting or reading spaces desktops, only the active desktop when it is run. Testing on macOS 10.15.6

**Comment by scriptingosx** [comment]
desktoppr has never been able to work with multiple spaces.

Unfortunately, I don't know of a way to read or set the desktop for different, non-active spaces or desktops. When someone figures this out in a way that I can re-create I would love to add that feature.

This is related to #2
